esphome:
  name: ender
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  
mqtt:
  broker: octopi.local
  port: 1883
  on_message:
    topic: ender/mains
    qos: 0
    then:
      - logger.log: "shutting down in 30 seconds"
      - delay: 30s
      - switch.turn_off: mains

captive_portal:

# Enable logging
logger:

ota:
  
output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

switch:
  - platform: output
    name: mains
    id: mains
    output: relay_1
    
status_led:
  pin:
    number: GPIO13
    inverted: yes

binary_sensor:
  - platform: gpio
    name: button
    pin:
      number: GPIO0
    on_press:
      then:
        - if:
            condition:
              switch.is_on: mains
            then:
              - logger.log: "shutting down in 30 seconds"
              - mqtt.publish:
                  topic: octoprint/shutdown
                  payload: "OFF"
              - delay: 30s
              - switch.turn_off: mains
            else:
              - logger.log: "start up mains"
              - switch.turn_on: mains

